### ISSUE TITLE
Sphinx docs

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/RPLCD#10]
On Readthedocs.

**Comment by thijstriemstra** [comment]
I can take care of this. Feel free to assign this ticket to me.

**Comment by dbrgn** [comment]
I'll set up the basic structure tomorrow, but then I'd be happy about documentation pull requests :)

**Comment by thijstriemstra** [comment]
Ok, in that case, enjoy ;)

**Comment by dbrgn** [comment]
Work in progress in #37.

Regarding your comment about `0.1.0`, that's probably right. Maybe we can make it `0.9.0` and switch to `1.0.0` if no bugs appear.
