### ISSUE TITLE
how to writh forign language to the lcd ?

### ISSUE THREAD

**Issue by machine85** [dbrgn/RPLCD#105]
Hello,
i am try to writh hebrew to the lcd
i try to use:
>>> bstring = 'Temperature: 30°C'
>>> bstring
'Temperature: 30Â°C'
>>> bstring.decode('utf-8')
u'Temperature: 30°C

but in python 3 i get the error :
TypeError: decoding str is not supported

thanks
Tom

**Comment by dbrgn** [comment]
In Python 3, a regular string is already a unicode string. You don't need to do any decoding when writing it to the display, RPLCD always wants unicode strings when writing text to the display.

(Note that I'm not aware of any LCD that supports hebrew characters.)

**Comment by machine85** [comment]
Thank you ^(y)
