### ISSUE TITLE
Convenience functions for newline / carriage return

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/RPLCD#11]
Convenience functions. Easier to use than `write_string('\n')` or `cursor_pos = (cursor_pos.row + 1, cursor_pos.col)`.

```
def nl():
    ...

def cr():
    ...
```

Or should they be spelled as `newline` and `carriage_return` instead?

**Comment by thijstriemstra** [comment]
+1 (for newline and carriage_return)
