### ISSUE TITLE
API Spotfy

### ISSUE THREAD

**Issue by cosminiq** [dbrgn/RPLCD#116]
hi. sorry for my bad english, first:)
I use RasSpotfy on my RaspBerry Pi 3 + DAC Wolfson audio card + LCD 20X4 i2c, so...
Can i implement the API from Spotfy and display the track name on my LCD?? WHERE i modify the main code?

i am sure i saw something like that on the web but i don't find it anymore.

p.s. you are doing a great job. 
my respect!

**Comment by dbrgn** [comment]
You can display any text on the LCD. This library has nothing to do with Spotify, if you want Spotify integration you will have to use a Spotify library.

For instructions how to use RPLCD, please see https://rplcd.readthedocs.io/
