### ISSUE TITLE
Writing not possible, just background light control

### ISSUE THREAD

**Issue by rodentooth** [dbrgn/RPLCD#119]
I use the backpack PCF8574**t** and a 20x4 blue white display. 
I have all required prerequisites, the i2c detects the device and the contrast is set to high. 
Yet, my display shows this on init, clear and any other command:

https://i.stack.imgur.com/YL57y.jpg

Backlight control works

**Comment by dbrgn** [comment]
Hm, my guess would be that the contrast is set too high?

Do you control it using a pot on the backpack?

**Comment by rodentooth** [comment]
Hi Daniel

Many thanks for your reply. I tried twiddling around with the contrast, not helping either. only the two full bars like in the image.
The contrast is set on the backback, yes

**Comment by dbrgn** [comment]
Ok, then I don't know unfortunately what causes this, sorry. You might want to check whether there are significant differences between the PCF8574 and the PCF8574t.
