### ISSUE TITLE
Rethink Encoding

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/RPLCD#15]
See http://www.raspberrypi.org/forums/viewtopic.php?p=537907#p537907.

**Comment by dbrgn** [comment]
I think this can be done using a custom codec (see https://docs.python.org/3/library/codecs.html#codecs.register).

**Comment by dbrgn** [comment]
I started implementing Python codecs for the HD44780-A00 and HD44780-A02 character maps described in the data sheet.

Code can be found here: https://github.com/dbrgn/RPLCD/tree/codec/RPLCD/codecs I'm not yet sure how this fits into the complete picture. Also, sometimes mapping multiple characters to the same output would be desired, in that case I'll probably have to get away from using `codecs.charmap_build`.

There are also some characters that I couldn't map yet so far (e.g. 0xb4 in the A02 character map).

**Comment by rfarley3** [comment]
+1

**Comment by dbrgn** [comment]
This can be closed thanks to #40 :)
