### ISSUE TITLE
Wiring Docs

### ISSUE THREAD

**Issue by dbrgn** [dbrgn/RPLCD#22]
There should be a photo and documentation on how to properly wire the LCD.

A link to this https://learn.adafruit.com/character-lcds/wiring-a-character-lcd might be enough.

**Comment by rameshg87** [comment]
Wondering if this would solve the issue:
https://github.com/dbrgn/RPLCD/pull/23

I too felt how to wire up things was missing, wrote some documentation, raised pull request, and then saw this issue raised :)

**Comment by dbrgn** [comment]
Fixed in #23.
