### ISSUE TITLE
Offset line 3 and 4

### ISSUE THREAD

**Issue by iUltimateLP** [dbrgn/RPLCD#24]
Hey, first of all, your library is great, but I have a problem with it.
I already worked with this LCD (16x4) with the Arduino, and I had the same problem there, the 3rd and 4th line is offset by 4 characters, so where a letter would be in the first col, it is in the 4th col. Back with the Arduino, I fixed it by changing the RAM addresses for every single line, whereas the original address in the code was 0xXX, and I needed to change it to 0xYY (sorry, don't remember the values), which can be looked up in the datasheet of the LCD. So I searched through your code, but I didn't find any variable to specify the RAM adress for line 3 and 4, so could you add such variables in the code? Would be very handy, thanks!

Edit: If I write something in the 3rd line, it is offset 4 cols, as I said. If I shift the display then by -4, so 4 cols behind, the 3rd and 4th lines are then perfect..

**Comment by iUltimateLP** [comment]
Oh, I am actually that dumb and gave a wrong col count :joy: Silly me

**Comment by dbrgn** [comment]
Hehe, that's what I thought :) Good that you found the fix yourself.
