### ISSUE TITLE
+5V and GND pins reversed

### ISSUE THREAD

**Issue by MarcoMiltenburg** [dbrgn/RPLCD#25]
Under the section [Wiring up Pi with LCD display](https://github.com/dbrgn/RPLCD#wiring-up-pi-with-lcd-display) the pins 1 and 2 are reversed. It says that pin 1 should be connected to the plus and pin 2 to GND but as far as I know and have tested, it should be reversed. Pin 1 is Vss and thus ground, pin2 is Vdd and thus plus (5 volt).

**Comment by dbrgn** [comment]
I think you're right, thanks for noting!
