### ISSUE TITLE
20 x 4 demo typo

### ISSUE THREAD

**Issue by thijstriemstra** [dbrgn/RPLCD#33]
When I run the 20x4 test it actually reports this:

```diff
diff --git a/test_20x4.py b/test_20x4.py
index 70c6d58..854f386 100755
--- a/test_20x4.py
+++ b/test_20x4.py
@@ -127,8 +127,8 @@ lcd.write_string('12345678901234567890\r\n2nd line')
 input('The first line should be filled with numbers, the second line should show "2nd line"')
 
 lcd.clear()
-lcd.write_string('999456..............\n\r\n\n\n123')
-input('The display should show "123456...................." on the first line')
+lcd.write_string('123456..............\n\r\n\n\n123')
+input('The display should show "123456...................." on the first line and "123" on the last line')
 
 lcd.clear()
 lcd.backlight = False
```

**Comment by dbrgn** [comment]
Hm, the test is written correctly. The display has 4 rows, but there are five newlines, so it should wrap back to the first line and overwrite the `999` part with `123`.

The dots are there to fill up the row. That triggers an auto linebreak, but the manual newline following the auto linebreak should be disabled. Auto linebreaks can be disabled by setting `auto_linebreaks` in the `CharLCD` constructor to `False`.

Does that not work for you, @thijstriemstra? I guess I'll have to search my 20x4 LCD to test this out. Maybe there's a bug in the auto-linebreak + manual newline control handling. It's tricky code :)
