### ISSUE TITLE
Compatible LCDs

### ISSUE THREAD

**Issue by cfaessler** [dbrgn/RPLCD#41]
What about adding a list of tested devices/controllers in the README? I know there are minor differences, although devices are HD44780 compatible. Commands are usually not a problem, but addresses (such as CGRAM) could be.

**Comment by dbrgn** [comment]
The problem is that most LCDs don't really have a product name, right?

**Comment by cfaessler** [comment]
No they don't. But the controllers are known.

**Comment by dbrgn** [comment]
That's true. Feel free to start such a list, the best place for it would probably be a new page [in the docs](https://github.com/dbrgn/RPLCD/tree/master/docs), with a link from README.

**Comment by brantje** [comment]
I think a nice list can be found [here](https://www.aliexpress.com/wholesale?catId=0&SearchText=i2c+lcd) (aliexpress).

**Comment by dbrgn** [comment]
> I think a nice list can be found here (aliexpress).

Just because all those displays use I2C does not mean that the protocol is compatible. It usually is, but there's not really a simple way to find out before trying it.

**Comment by brantje** [comment]
Good catch. Maybe make a wiki page with tested lcds?
I have some at home, but need to test them first with this lib.

**Comment by dbrgn** [comment]
I also have a few at home, but the main issue is, how do you identify an LCD? They're all no-brand, so the only thing we can differentiate is the I²C port expander (which we already list [here](https://github.com/dbrgn/RPLCD#supported-ic-port-expanders). And that only works if the LCD uses I²C, not parallel mode.

**Comment by dbrgn** [comment]
Closing this for now, but pull requests are welcome.
