### ISSUE TITLE
Error when changing to GPIO.BCM mode using the example

### ISSUE THREAD

**Issue by 4QStudios** [dbrgn/RPLCD#61]
hi, every time i want to initialize the lcd in BCM mode for the pins it fails, is this hardcoded to work only in BOARD mode?
the file is  gpio.py

**Comment by GoranLundberg** [comment]
I got it working in BCM mode. What does your code look like?

**Comment by 4QStudios** [comment]
this is the output when i set the BCM mode
<img width="689" alt="screen shot 2017-05-18 at 2 01 04 pm" src="https://cloud.githubusercontent.com/assets/14880293/26216578/96790026-3bd2-11e7-9a2e-b3c362ca705d.png">

Here you can see the code
<img width="963" alt="screen shot 2017-05-18 at 2 01 23 pm" src="https://cloud.githubusercontent.com/assets/14880293/26216577/9676fb8c-3bd2-11e7-9171-d46f8a4ee680.png">

**Comment by GoranLundberg** [comment]
You have the wrong data pins. pins_data needs to be the BCM numbering on the Pi. For example 0 does not exist. Check this site for BCM numbering. https://pinout.xyz/

**Comment by 4QStudios** [comment]
im a retard, i was using the wPi number scheme instead of the BCM, im closing this
