### ISSUE TITLE
Online docs are out of date

### ISSUE THREAD

**Issue by ozarchie** [dbrgn/RPLCD#66]
The link to the online readthedocs points to a page that is out of date.
http://rplcd.readthedocs.io/en/stable/api.html
This doc shows a getting started example and API reference that are not consistent with the library.
This one pointing to a pdf is correct:
https://media.readthedocs.org/pdf/rplcd/latest/rplcd.pdf

**Comment by dbrgn** [comment]
Yeah, that's because I planned to release the newest version of the library a while ago and somehow didn't find time for it.

I'll try to do it tonight, then it should be in sync again :)

**Comment by ozarchie** [comment]
Thanks Danilo, great library.  Thanks so much. Cheers John

**Comment by dbrgn** [comment]
1.0.0 is released, links to documentation are updated :)

> Thanks Danilo, great library.  Thanks so much. Cheers John

Thank you, feedback from users is very appreciated :)
