### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by jafal1** [dbrgn/RPLCD#75]
hi all
 using arduino
 
i need program reads binary bits from 16 bit up to 128 in serial

and convert the bits to decimal using the command tvout

any one can help please

**Comment by dbrgn** [comment]
Hi, this is a Raspberry Pi library, so you need Linux which won't run on Arduino.

Maybe ask in the [Arduino Forum](https://forum.arduino.cc/) or [on Reddit](https://www.reddit.com/r/arduino/).
