### ISSUE TITLE
cannot import CursorMode

### ISSUE THREAD

**Issue by noriyukiSuzuki** [dbrgn/RPLCD#79]
I'm using Raspberry pi 3 with Rasbian and I just follow this tutorial : http://www.circuitbasics.com/raspberry-pi-lcd-set-up-and-programming-in-python/

When I write  

    from RPLCD import CharLCD
    from RPLCD import CursorMode

I get this error
`ImportError: cannot import name CursorMode`

I've tried with Python 2.7.13 and Python 3.5.3, but both give same error.
I've already reinstall library but no any difference.
Do you have any advises?
(aside from this problem, it can show the text on lcd display without any problem )

**Comment by dbrgn** [comment]
Alternatively you could install the previous version of RPLCD that is still compatible:

    pip install RPLCD==0.9.0

**Comment by noriyukiSuzuki** [comment]
it works, thank you for super quick response.

**Comment by dbrgn** [comment]
Great to hear that it works :)
