### ISSUE TITLE
missing global variable in test

### ISSUE THREAD

**Issue by bazooka07** [dbrgn/RPLCD#87]
Hello,
In the function run() in the RPLCD_Tests/entrypoint file, I have to declare options as global for working
with Python 3.6.6 with Ubuntu Bionic 18.4.
I have test with success on the Rock64 SBC with a 20x4 LCD.

**Comment by dbrgn** [comment]
Hi. What exactly do you mean? Did you just prepend the `global` keyword to lines 31 and 32?

**Comment by bazooka07** [comment]
No. At line #170, insert a new line and declare "options" as global.
If not, a local variable "options" is set in the try statement and the global variable "options" declared at line #31 is unchanged.
The global variable at line#31 is used by the "options_pop" function.
