### ISSUE TITLE
smbus2 support

### ISSUE THREAD

**Issue by joscha** [dbrgn/RPLCD#89]
Any chance a pull request that allows usage of `smbus2` as a drop-in replacement would be accepted? Potentially also as a fallback when `smbus` can not be loaded (or as a favored in case `smbus2` is installed). I am trying to make RPLCD work on Python 3 with balena and I am having a hard time getting the smbus packages in the right state.

**Comment by dbrgn** [comment]
Hi. What are the advantages of `smbus2` over `smbus`?

**Comment by dbrgn** [comment]
Ah, that is cool :slightly_smiling_face:

I could imagine something like this working well:

```python
try:
    import smbus
except ImportError:
    import smbus2 as smbus
```

What do you think?

**Comment by joscha** [comment]
Yep, that would be great!

**Comment by dbrgn** [comment]
Would you be willing to create a pull request?

Simply updating all the imports would be sufficient :slightly_smiling_face: Additionally, updating the README / Docs to say "smbus or smbus2" would be nice too.

**Comment by joscha** [comment]
Of course, will do this evening (I am UTC+10).

**Comment by joscha** [comment]
PR is in https://github.com/dbrgn/RPLCD/pull/90 - let me know if there is any other place I should mention smbus2
