### ISSUE TITLE
Big Fonts

### ISSUE THREAD

**Issue by riker65** [dbrgn/RPLCD#99]
Hi
could this be an enhancement?
Could you support big fonts 
as arduino does.
https://forum.arduino.cc/index.php?topic=346971.msg2393467#msg2393467

Thanks T

**Comment by dbrgn** [comment]
Direct support is not currently planned, but you can implement it yourself by using custom characters. See https://rplcd.readthedocs.io/en/stable/usage.html#creating-custom-characters for more information on how to create and use custom characters.

**Comment by riker65** [comment]
Hi
ok thanks 
will check this
